CREATE TABLE IF NOT EXISTS product (
    product_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_category VARCHAR(50) NOT NULL,
    product_name VARCHAR(100) UNIQUE NOT NULL,
    product_price NUMERIC(10, 2) NOT NULL CHECK (product_price > 0),
    product_image_url TEXT,
    descrip VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS inventory (
    product_id BIGINT PRIMARY KEY,
    current_qty INT NOT NULL DEFAULT 0,

    CONSTRAINT fk_inventory_product
        FOREIGN KEY (product_id)
        REFERENCES product(product_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS cafe_order (
    order_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    total_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
);

CREATE TABLE IF NOT EXISTS order_item (
    order_item_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INT NOT NULL CHECK (quantity > 0),
    price_at_purchase NUMERIC(10,2) NOT NULL,

    CONSTRAINT fk_order FOREIGN KEY (order_id) REFERENCES cafe_order(order_id) ON DELETE CASCADE,
    CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES product(product_id) ON DELETE CASCADE
);

