CREATE TABLE IF NOT EXISTS product (
    product_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_category VARCHAR(50) NOT NULL,
    product_name VARCHAR(100) UNIQUE NOT NULL,
    product_price NUMERIC(10, 2) NOT NULL CHECK (product_price > 0),
    product_image_url TEXT,
    descrip VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS inventory (
    product_id BIGINT PRIMARY KEY,
    current_qty INT NOT NULL DEFAULT 0,

    CONSTRAINT fk_inventory_product
        FOREIGN KEY (product_id)
        REFERENCES product(product_id)
        ON DELETE CASCADE
);

-- order and orderItem to be implemented later